let shopItemsData = [
    {
        id: "jfhgbvnscs1",
        name: "Casual Shirt",
        price: 45,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img/img_1.jpg",
    },
    {
        id: "ioytrhndcv2",
        name: "Office Shirt",
        price: 100,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img/img_2.jpg",
    },
    {
        id: "wbncxbsn3",
        name: "T Shirt",
        price: 25,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img/img_1.jpg",
    },
    {
        id: "thyfhbcv4",
        name: "Mens Suit",
        price: 300,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img/img_4.jpg",
    },
    {
        id: "thiecbaw5",
        name: "Mens Tie",
        price: 25,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img/img_5.jpg",
    },
    {
        id: "iuersadjk6",
        name: "Casual shoes",
        price: 200,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img/img_6.jpg",
    },
    {
        id: "bvcbvzdhadjk7",
        name: "black suit",
        price: 450,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img/img_7.jpg",
    },
    {
        id: "trfoiwfcndj8k",
        name: "polo shirt",
        price: 45,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img/img_8.jpg",
    },
    {
        id: "cbvxbcldk9",
        name: "denim shirt",
        price: 85,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img/hi.jpg",
    },
    {
        id: "oiohuihb10",
        name: "denim pants",
        price: 120,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img/istockphoto-1267191071-612x612.jpg",
    },
    {
        id: "oiobjhib11",
        name: "basic cap",
        price: 35,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img/img_4.jpg",
    },
    {
        id: "jewyib12",
        name: "basic cap",
        price: 35,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img/img_5.jpg",
    },
    {
        id: "oewyiohb13",
        name: "basic cap",
        price: 35,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img/img_6.jpg",
    },
    {
        id: "oiopijyioh14",
        name: "basic cap",
        price: 35,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img/img_7.jpg",
    },
    {
        id: "oiopiohbib15",
        name: "basic cap",
        price: 35,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img/img_8.jpg",
    },
    {
        id: "ijewyiohbjhib16",
        name: "basic cap",
        price: 35,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img/img_9.jpg",
    },
    {
        id: "oiopijewb17",
        name: "basic cap",
        price: 35,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img/img_1.jpg",
    },
    {
        id: "oiopijewbjhib18",
        name: "basic cap",
        price: 35,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img/hi.jpg",
    },
  
   
   
];
